// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieTicketBooking.Infrastructure.Data;

#nullable disable

namespace MovieTicketBooking.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("MovieTicketBooking.Domain.Entities.BookedSeat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Row")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookingId", "Row", "Number")
                        .IsUnique();

                    b.ToTable("BookedSeats");
                });

            modelBuilder.Entity("MovieTicketBooking.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BookedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ShowTimeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShowTimeId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("MovieTicketBooking.Domain.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A thief who steals corporate secrets through dream-sharing technology.",
                            DurationMinutes = 148,
                            Genre = "Sci-Fi",
                            Rating = "PG-13",
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Batman faces the Joker in Gotham City.",
                            DurationMinutes = 152,
                            Genre = "Action",
                            Rating = "PG-13",
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Explorers travel through a wormhole in space.",
                            DurationMinutes = 169,
                            Genre = "Sci-Fi",
                            Rating = "PG-13",
                            Title = "Interstellar"
                        });
                });

            modelBuilder.Entity("MovieTicketBooking.Domain.Entities.Screen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SeatsPerRow")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TheaterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalRows")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TheaterId");

                    b.ToTable("Screens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Screen 1",
                            SeatsPerRow = 8,
                            TheaterId = 1,
                            TotalRows = 5
                        },
                        new
                        {
                            Id = 2,
                            Name = "Screen 2",
                            SeatsPerRow = 6,
                            TheaterId = 1,
                            TotalRows = 4
                        },
                        new
                        {
                            Id = 3,
                            Name = "Screen 1",
                            SeatsPerRow = 10,
                            TheaterId = 2,
                            TotalRows = 6
                        });
                });

            modelBuilder.Entity("MovieTicketBooking.Domain.Entities.ShowTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScreenId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("ScreenId");

                    b.ToTable("ShowTimes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 12.50m,
                            MovieId = 1,
                            ScreenId = 1,
                            StartTime = new DateTime(2026, 9, 7, 18, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 14.00m,
                            MovieId = 2,
                            ScreenId = 1,
                            StartTime = new DateTime(2026, 9, 7, 21, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 15.00m,
                            MovieId = 3,
                            ScreenId = 3,
                            StartTime = new DateTime(2026, 9, 7, 19, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("MovieTicketBooking.Domain.Entities.Theater", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Theaters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "123 Main Street",
                            Name = "CineMax Downtown"
                        },
                        new
                        {
                            Id = 2,
                            Location = "456 Mall Road",
                            Name = "Star Cinema Mall"
                        });
                });

            modelBuilder.Entity("MovieTicketBooking.Domain.Entities.BookedSeat", b =>
                {
                    b.HasOne("MovieTicketBooking.Domain.Entities.Booking", "Booking")
                        .WithMany("Seats")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("MovieTicketBooking.Domain.Entities.Booking", b =>
                {
                    b.HasOne("MovieTicketBooking.Domain.Entities.ShowTime", "ShowTime")
                        .WithMany("Bookings")
                        .HasForeignKey("ShowTimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShowTime");
                });

            modelBuilder.Entity("MovieTicketBooking.Domain.Entities.Screen", b =>
                {
                    b.HasOne("MovieTicketBooking.Domain.Entities.Theater", "Theater")
                        .WithMany("Screens")
                        .HasForeignKey("TheaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Theater");
                });

            modelBuilder.Entity("MovieTicketBooking.Domain.Entities.ShowTime", b =>
                {
                    b.HasOne("MovieTicketBooking.Domain.Entities.Movie", "Movie")
                        .WithMany("ShowTimes")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieTicketBooking.Domain.Entities.Screen", "Screen")
                        .WithMany("ShowTimes")
                        .HasForeignKey("ScreenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("MovieTicketBooking.Domain.Entities.Booking", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("MovieTicketBooking.Domain.Entities.Movie", b =>
                {
                    b.Navigation("ShowTimes");
                });

            modelBuilder.Entity("MovieTicketBooking.Domain.Entities.Screen", b =>
                {
                    b.Navigation("ShowTimes");
                });

            modelBuilder.Entity("MovieTicketBooking.Domain.Entities.ShowTime", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("MovieTicketBooking.Domain.Entities.Theater", b =>
                {
                    b.Navigation("Screens");
                });
#pragma warning restore 612, 618
        }
    }
}
